In [4]:
import pandas as pd

data_path = "D:/Users/Documents/Jupyter/BreastCancerClassification/data/breast-cancer.data"

BreastCancer = pd.read_csv(data_path)

BreastCancer.columns = ["Class", "Age", "menopause", "tumor-size", "inv-nodes", "node-caps", "deg-malig", "breast", "breast-quad", "irradiat"]

BreastCancer.head()

,Class,Age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
2,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
3,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no
4,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,left,left_low,no

In [5]:
BreastCancer.shape

(285, 10)

In [6]:
BreastCancer.info()

BreastCancer.isnull().sum()

BreastCancer["Class"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 285 entries, 0 to 284
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Class        285 non-null    object
 1   Age          285 non-null    object
 2   menopause    285 non-null    object
 3   tumor-size   285 non-null    object
 4   inv-nodes    285 non-null    object
 5   node-caps    285 non-null    object
 6   deg-malig    285 non-null    int64
 7   breast       285 non-null    object
 8   breast-quad  285 non-null    object
 9   irradiat     285 non-null    object
dtypes: int64(1), object(9)
memory usage: 22.4+ KB

Class
no-recurrence-events    200
recurrence-events        85
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import OneHotEncoder

categorical_columns = BreastCancer.select_dtypes(include = ["object"]).columns.tolist()

encoder = OneHotEncoder(sparse_output = False)

one_hot_encoded = encoder.fit_transform(BreastCancer[categorical_columns])

one_hot_BreastCancer = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

BreastCancer_encoded = pd.concat([BreastCancer, one_hot_BreastCancer], axis = 1)

BreastCancer_encoded = BreastCancer_encoded.drop(categorical_columns, axis=1)

print(BreastCancer_encoded.head(5))

   deg-malig  Class_no-recurrence-events  Class_recurrence-events  Age_20-29  \
0          2                         1.0                      0.0        0.0
1          2                         1.0                      0.0        0.0
2          2                         1.0                      0.0        0.0
3          2                         1.0                      0.0        0.0
4          2                         1.0                      0.0        0.0

   Age_30-39  Age_40-49  Age_50-59  Age_60-69  Age_70-79  menopause_ge40  ...  \
0        0.0        1.0        0.0        0.0        0.0             0.0  ...
1        0.0        1.0        0.0        0.0        0.0             0.0  ...
2        0.0        0.0        0.0        1.0        0.0             1.0  ...
3        0.0        1.0        0.0        0.0        0.0             0.0  ...
4        0.0        0.0        0.0        1.0        0.0             1.0  ...

   breast_left  breast_right  breast-quad_?  breast-quad_central  \
0          0.0           1.0            0.0                  0.0
1          1.0           0.0            0.0                  0.0
2          0.0           1.0            0.0                  0.0
3          0.0           1.0            0.0                  0.0
4          1.0           0.0            0.0                  0.0

   breast-quad_left_low  breast-quad_left_up  breast-quad_right_low  \
0                   0.0                  0.0                    0.0
1                   1.0                  0.0                    0.0
2                   0.0                  1.0                    0.0
3                   0.0                  0.0                    1.0
4                   1.0                  0.0                    0.0

   breast-quad_right_up  irradiat_no  irradiat_yes
0                   1.0          1.0           0.0
1                   0.0          1.0           0.0
2                   0.0          1.0           0.0
3                   0.0          1.0           0.0
4                   0.0          1.0           0.0

[5 rows x 43 columns]

In [16]:
BreastCancer_encoded.describe()

,deg-malig,Class_no-recurrence-events,Class_recurrence-events,Age_20-29,Age_30-39,Age_40-49,Age_50-59,Age_60-69,Age_70-79,menopause_ge40,...,breast_left,breast_right,breast-quad_?,breast-quad_central,breast-quad_left_low,breast-quad_left_up,breast-quad_right_low,breast-quad_right_up,irradiat_no,irradiat_yes
count,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,...,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000,285.000000
mean,2.045614,0.701754,0.298246,0.003509,0.122807,0.315789,0.336842,0.200000,0.021053,0.452632,...,0.529825,0.470175,0.003509,0.073684,0.382456,0.340351,0.084211,0.115789,0.761404,0.238596
std,0.737351,0.458293,0.458293,0.059235,0.328793,0.465647,0.473462,0.400704,0.143812,0.498627,...,0.499988,0.499988,0.059235,0.261716,0.486842,0.474661,0.278192,0.320535,0.426975,0.426975
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,3.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,...,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
max,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000